version: '3'
 
services:
 
    php:
        image: pjaun/php72-fpm
        container_name: php
        ports:
            - 9000:9000
        volumes:
            - ./www:/var/www/html
            - ./conf/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
        environment:
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        restart: always
 
    nginx:
        image: nginx:${NGINX_VERSION}
        container_name: nginx
        ports:
            - 80:80
        volumes:
            - ./www:/var/www/html
            - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./sites:/etc/nginx/sites-enabledls
        depends_on:
            - php
        restart: always
 
    mysql:
        image: mysql:${MYSQL_VERSION}
        container_name: mysql
        ports:
           - 3306:3306
        depends_on:
            - php
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes: 
            - ./data:/var/lib/mysql
        restart: always

    myadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports: 
            - 88:80
        depends_on: 
            - php
            - mysql
        environment: 
            - PMA_ARBITRARY=1
            - PMA_HOST=${MYSQL_HOST}
        links: 
            - mysql
        restart: always
